export {default as Home} from "./Home"
export {default as Suporte} from "./Suporte"
export {default as Forum} from "./Foruns"
export {default as Premium} from "./Premium"
export {default as Planos} from "./Planos"